name: Build and Release Project
on:
  push:
    tags:
      - 'v*'
jobs:
  all:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.21'
    - name: Init Project
      run: |
        mkdir build
        cd build
        cmake -S ..
        make

    - name: Create and move to fatJar dir
      run: mkdir fatJar && cd fatJar
    - name: Extract app
      run: jar xf ../../PersonalFinance.jar
    - name: Extract jOpenDocument
      run: jar xf ../../jOpenDocument.jar
    - name: Repackage jar
      run: jar cef Main PersonalFinanceFat.jar
    - name: Move to root dir
      run: mv PersonalFinanceFat.jar ../../

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "PersonalFinanceFat.jar"